apiVersion: v1
kind: ConfigMap
metadata:
  name: oslash
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: oslash
  AUTH_SECRET_KEY: secret-key_secret-key_secret-key_secret-key_secret-key_secret-key_secret-key_secret-key_secret-key_secret-key_secret-key
  COUCHBASE_HOST: couchbase-srv
  COUCHBASE_USER: Administrator
  COUCHBASE_PASSWORD: password
  COUCHBASE_BUCKET: oslash
